name: Node.js Docker CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Get the source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build Docker image
      - name: Build Docker image
        run: docker build -t my-node-app .

      # 5. Check Docker image
      - name: Check Docker image
        run: docker images my-node-app
